### ISSUE TITLE
[Bug] Install Error

### ISSUE THREAD

**Issue by zero77** [aminpaks/qbittorrent-web-ui#11]
I may be doing something wrong but, i get the below errors when i try to install from the released version although it works perfectly when i run from the git version.

npm install
npm WARN saveError ENOENT: no such file or directory, open ~/package.json
npm WARN enoent ENOENT: no such file or directory, open ~/package.json
npm WARN public No description
npm WARN public No repository field.
npm WARN public No README data
npm WARN public No license field.

npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path ~/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open ~/package.json
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!    ~/.npm/_logs/2021-01-18T12_39_46_544Z-debug.log

**Comment by aminpaks** [comment]
Interesting, I haven't verified the content of release source code. I assume they must be identical.

Would you double check if the content of release is identical with master?

**Comment by zero77** [comment]
ls qbittorrent-web-ui
babel.config.js  dev.js        package.json       public     src            webpack            yarn.lock
build-reports    node_modules  package-lock.json  README.md  tsconfig.json  webpack.config.js

ls public           (v0.0.1-beta.3.zip)
0.bundle.c7da36331ded55fd3031.js      bundle.9fa4c5cfec8f038eac91.js      icon512.png    package-lock.json
0.bundle.c7da36331ded55fd3031.js.map  bundle.9fa4c5cfec8f038eac91.js.map  index.html
2.bundle.387b5b69898b9210d9f2.js      favicon.ico                         lang
2.bundle.387b5b69898b9210d9f2.js.map  icon192.png                         manifest.json

**Comment by aminpaks** [comment]
So the release source code should contain the same content. But the build artifacts `v0.0.1-beta.3.zip` should only include the application that you would use with qbt.

I'm gonna write up how to use the build artifacts in Wiki but JFYI:
1. Extract `v0.0.x-beta.x.zip`
2. You will have a `public` folder
3. Move it somewhere that QBT has read access
4. Set the path for WebUI in QBT to the folder that contains `public` folder

**Comment by zero77** [comment]
Thanks for the help, i have now got this working.

Does this mean that you can only have one ui and not the two side by side for testing and comparison . 
As it's possible to run both when compiling and running from master.

**Comment by aminpaks** [comment]
@zero77 

To make that possible QBT has to change a little bit how its core api works. [This](https://github.com/qbittorrent/qBittorrent/issues/14130) is basically the discussion in which how this can happen.

**Comment by zero77** [comment]
Thanks
