### ISSUE TITLE
Blank page in webOS browser

### ISSUE THREAD

**Issue by qarkai** [aminpaks/qbittorrent-web-ui#20]
Blank page in webOS browser. It's kind of really old version (~54) of Chromium.
Page loads correctly in modern browsers (both desktop and mobile). Official Web UI in webOS works correctly too.
I use [2nd minor release](https://github.com/aminpaks/qbittorrent-web-ui/releases/tag/v0.2.0) and qBittorrent v4.3.3.

**Comment by aminpaks** [comment]
@qarkai
The builds are not compatible with older versions of Chrome. I have plans to fix this soon but don't wanna focus on it till the main functionality of the app is complete.

I'll keep this open to follow up. Sorry for any inconvenience.

I'm open to PR if you wanna contribute :)

**Comment by qarkai** [comment]
FYI: https://github.com/CzBiX/qb-web/issues/91#issuecomment-778757977 Probably you'll 'wontfix' it too.

**Comment by aminpaks** [comment]
No I will fix it just not now. This requires to provide missing functionality to the old browsers. I haven't looked into that version of Chromium but I'm confident that it's not as bad as IE11 so it will be fixed.

**Comment by aminpaks** [comment]
@qarkai try this release
https://github.com/aminpaks/qbittorrent-web-ui/releases/tag/v0.4.0

It should fixes your issues. Please report if you're still encountering it.

**Comment by qarkai** [comment]
It works now, thanks!
